### ISSUE TITLE
Nothing publishes to the "story-scroll-section" topic.

### ISSUE THREAD

**Issue by torrin47** [Esri/storymap-cascade#1]
This section never fires, because nothing publishes to the "story-scroll-section" topic.

topic.subscribe("story-scroll-section", function(cfg){
    console.log("The section", cfg.index, "is now active");
  });

It works just fine subscribing to the "story-navigated-section" topic, though. Should be an easy fix in either direction.

**Comment by glazou** [comment]
Thanks for reporting. Yes the correct event is `story-navigated-section`, updated the documentation and sample in index.html
