### ISSUE TITLE
Trying to remove index.html in the URL

### ISSUE THREAD

**Issue by thehappydinoa** [Esri/storymap-cascade#12]
I am struggling with removing `index.html` from the link. I want to have [`domain.com`](domain.com) show my story map, but when I go to our home page it takes me to [`domain.com/index.html`](domain.com/index.html). Is this even possible?

**Comment by skitterm** [comment]
Hi Aidan,

Yes, this is possible. You can remove [this line](https://github.com/Esri/storymap-cascade/blob/master/src/app/storymaps/common/Core.js#L218) and the app will not append `index.html` on the end of your URL.

**Comment by thehappydinoa** [comment]
@skitterm thank you so much, that did the trick!
