### ISSUE TITLE
grunt dev not work

### ISSUE THREAD

**Issue by ly2015** [Esri/storymap-cascade#14]
In the product mode the program can run perfectly, but there are errors in the development mode, the error message is as follows：
![error](https://user-images.githubusercontent.com/15793112/40966884-43c280c4-68e4-11e8-892f-a4bcf1fa7025.png)

**Comment by skitterm** [comment]
Hi @ly2015, this issue is now fixed with today's release. Let us know if you are still seeing this issue after updating.
