### ISSUE TITLE
Latin Extended fonts

### ISSUE THREAD

**Issue by qbns** [Esri/storymap-cascade#2]
It seems that the project depends on Open Sans and Droid Serif webfonts without extended Latin character set. Are there any plans for subsituting current fonts with extended ones?
I've noticed that latin-ext is not available for Droid Serif so it would require to choose different font for sections.

**Comment by oevans** [comment]
Hi -- we added additional language packs to Cascade in the December 2016 release, so you should see that it supports extended character sets now.
