### ISSUE TITLE
Build fails because clipboard.js missing

### ISSUE THREAD

**Issue by regan-sarwas** [Esri/storymap-cascade#3]
After `npm install`, `grunt` fails:

    $ grunt
    ....
    Running "requirejs:builder" (requirejs) task
    Error: ENOENT: no such file or directory, open '/Users/regan/wwwroot/StoryMaps/storymap-cascade/src/lib//clipboard/dist/clipboard.js'
    In ... storymaps/common/ui/share/ShareURLPanel
    ....

This is likely due to the fact that `dist/` is in the python section of your [.gitignore](https://github.com/Esri/storymap-cascade/blob/f5e11803fe5e0cb9aa5a37314bbb7d19e40eabd4/.gitignore#L199) file, so these files may be in your local files, but never made it into the repo.

**Comment by lukewhyte** [comment]
Did you run `bower install` too or just `npm install`? I had to run `bower install --force` to get all those dependencies up to date locally.

**Comment by regan-sarwas** [comment]
`npm install` as documented in the [Readme](https://github.com/Esri/storymap-cascade/blob/f5e11803fe5e0cb9aa5a37314bbb7d19e40eabd4/README.md)

**Comment by skitterm** [comment]
Thanks for the heads-up, Regan. We'll update that in the next couple days.

**Comment by skitterm** [comment]
@regan-sarwas good catch on the .gitignore, sure enough that was the culprit. Clipboard.js's `dist` files now included in the project.
