### ISSUE TITLE
How to get h2 in transition

### ISSUE THREAD

**Issue by richardalain83** [Esri/storymap-cascade#6]
Hi, it's not a issue, i'm wondering how to select the currect section's transition h2. I want to replace it in jquery but i'm not able to properly access it.

![image](https://cloud.githubusercontent.com/assets/20196433/25146781/2afd27ba-2443-11e7-9e58-5ca4ea728dce.png)

from the documentation I see the getBookmark and getPreviewText methods but nothing else...

Thanks for the input

**Comment by ssylvia** [comment]
You can update the text for the current immersive section title with jQuery using:

```js
$('.section-immersive.active .title-text').html('New Example Text');
```

**Comment by richardalain83** [comment]
Thanks, worked the way I wanted :)
